[core_routers]
GRIDEDGE-CORE-01 ansible_host=devnetsandboxiosxec8k.cisco.com

[core_routers:vars]
ansible_user=architsharma08
ansible_password=6G-5W7Z_hsna
ansible_network_os=ios
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable