---
- name: Rollback Loopback200
  hosts: cisco_routers
  gather_facts: no

  tasks:
    - name: Remove Loopback200
      cisco.ios.ios_config:
        lines:
          - no interface Loopback200

    - name: Verify rollback
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: after_rollback

    - name: Print state after rollback
      debug:
        msg: "{{ after_rollback.stdout[0] }}"