---
- name: Network Audit Playbook
  hosts: cisco_routers
  gather_facts: no

  tasks:
    - name: Get interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Print interface output
      debug:
        msg: "{{ interface_output.stdout[0] }}"